### ISSUE TITLE
docker-compose缩进错误

### ISSUE THREAD

**Issue by Audi-dask** [go-zoox/chatgpt-for-chatbot-feishu#48]
```
services:
  chatgpt-for-chatbot-feishu:
  image: whatwewant/chatgpt-for-chatbot-feishu:latest
  platform: linux/amd64
  ports:
    - 8080:8080
  environment:
    APP_ID: "<YOUR_FEISHU_APP_ID>"
    APP_SECRET: "<YOUR_FEISHU_APP_SECRET>"
    OPENAI_API_KEY: "<YOUR_OPENAI_API_KEY>"
```

ERROR: In file './docker-compose.yaml', services 'image' must be a mapping not a string.

### 优化后的docker-compose的文件
```
# docker-compose.yaml
version: "3"

services:
  chatgpt-for-chatbot-feishu:
    image: whatwewant/chatgpt-for-chatbot-feishu:latest
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      APP_ID: clixxx
      APP_SECRET: Slyxxxxx
      OPENAI_API_KEY: sk-zxxxxxxxxx
```
